### ISSUE TITLE
Multi-line Notes (Shift+Enter) are not collapsed

### ISSUE THREAD

**Issue by raulf2012** [incace/matFlow#1]
The default behavior in Workflowy is to collapse notes of 2 lines or longer. This behavior seems to not work with this theme.

Is this intentional? And if how can you revert it back to the original behavior?

**Comment by incace** [comment]
I see what you are referring to. This didn't seem to exist, or I don't think it did, when I first developed the theme. I will add a fix for this.

**Comment by incace** [comment]
I've fixed this in the latest commit. Will update later today via Uso. Here is a preview. Let me know if there is anything I missed. 
![matflow-collapse](https://user-images.githubusercontent.com/61343/30830338-ece0a90c-a200-11e7-821c-ae983ec9f658.gif)
